version: '3.8'
services:
  it-inv:
    build: .
    ports:
      - "8089:8089"    # keduanya 8084
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8089
    volumes:
      - ./.env.local:/app/.env.local